# fly.toml app configuration file generated for weather-server on 2023-05-18T18:35:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weather-server"
primary_region = "waw"

[build]
  image = "weather-server"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
