package com.weather.server.service.impl;

import com.weather.server.domain.dto.UserApiKeyDto;
import com.weather.server.domain.dto.UserLoginDto;
import com.weather.server.domain.dto.UserLoginTokenDto;
import com.weather.server.domain.repository.UserRepository;
import com.weather.server.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;

public class UserServiceImpl implements UserService {

    private final UserRepository userRepository;

    @Autowired
    public UserServiceImpl(UserRepository userRepository) {
        this.userRepository=userRepository;
    }

    @Override
    public void createUser(UserLoginDto userLoginDto) {
        //verify email
        //verify password length
        //generate password hash
        //
        //or password is hash generated by client
        //verify if send password is hash
        //
        //userRepository.save();
    }

    @Override
    public UserLoginTokenDto loginUser() {
        //checkif email match
        //checkif passhash match
        //generateToken
        return null;
    }

    @Override
    public boolean generateApiKey(){
        //find user by token
        //generate api key and save in mongodb
        return true;
    }

    @Override
    public UserApiKeyDto readApiKey(String token) {
        //find user by token
        //read api key and send it back
        return null;
    }

    @Override
    public boolean checkToken() {
        //check if token exists in database
        return true;
    }
}
